/**
 * Compiles the Jack standard library in `os/jack` to the SM in `os/sm`, and
 * writes the module the emulator carries.
 *
 * The library is compiled by our own compiler with no privileges of any
 * kind: it is the largest Jack program we have, and compiling it is the
 * compiler's broadest test. `os/sm` is checked in so that nothing has to be
 * compiled to build the site, and `library.test.ts` fails if it is stale.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { compileClass, parseClass } from '@sm/jack'

export const OS_CLASSES = [
  'Array', 'Keyboard', 'Math', 'Memory', 'Output', 'Screen', 'String', 'Sys',
] as const

export interface BuiltLibrary {
  /** Class name to SM source. */
  readonly sm: Readonly<Record<string, string>>
  readonly warnings: readonly string[]
}

export function buildLibrary(jackDir: string): BuiltLibrary {
  const sm: Record<string, string> = {}
  const warnings: string[] = []
  const names = readdirSync(jackDir).filter((f) => f.endsWith('.jack')).sort()
  for (const file of names) {
    const source = readFileSync(join(jackDir, file), 'utf8')
    const result = compileClass(file, parseClass(file, source))
    sm[file.replace(/\.jack$/, '')] = result.sm
    warnings.push(...result.warnings)
  }
  return { sm, warnings }
}

/** The generated module, as text, so a test can compare without writing. */
export function libraryModule(built: BuiltLibrary): string {
  const entries = Object.entries(built.sm).map(
    ([name, sm]) => `  ${name}: ${JSON.stringify(sm)},`,
  )
  return [
    '/**',
    ' * The Jack standard library, compiled to SM.',
    ' *',
    ' * Generated by `npm run build:os` from `os/jack`. Do not edit: edit the',
    ' * Jack and regenerate. `library.test.ts` fails if this is stale.',
    ' */',
    'export const LIBRARY_SM: Readonly<Record<string, string>> = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

if (process.argv[1]?.endsWith('build-os.ts')) {
  const root = join(import.meta.dirname, '..', '..')
  const built = buildLibrary(join(root, 'os', 'jack'))
  for (const [name, sm] of Object.entries(built.sm)) {
    writeFileSync(join(root, 'os', 'sm', `${name}.sm`), sm)
  }
  writeFileSync(join(root, 'packages', 'sm-emulator', 'src', 'library.generated.ts'), libraryModule(built))
  for (const w of built.warnings) console.error(w)
  console.log(`wrote ${Object.keys(built.sm).length} classes`)
}
